# -*- coding: utf-8 -*-
"""GroupDNA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17GkOOYcODSi3rz0s6iZ2W1YSUggUskqV

# GroupDNA — WhatsApp Group Chat Decoded
"""

# AI used only for: datetime.strptime format hint. Everything else is mine.

import numpy as np
from datetime import datetime, timedelta

f = open('hostel_bois.txt', encoding='utf-8')
data = f.read()
f.close()
L = data.split('\n')
print("lines:", len(L))

M = []
sys, med, dele = 0, 0, 0

for x in L:
    if x == '':
        continue
    if len(x) > 7 and x[2] == '/' and x[5] == '/':
        a = x.split(' - ', 1)
        if len(a) < 2:
            sys += 1; continue
        b = a[1].split(': ', 1)
        if len(b) < 2:
            sys += 1; continue
        try:
            t = datetime.strptime(a[0], '%d/%m/%y, %H:%M')
        except:
            sys += 1; continue
        txt = b[1]
        if txt == '<Media omitted>':
            med += 1
            M.append((b[0], txt, t, 1, 0))
        elif txt == 'This message was deleted':
            dele += 1
            M.append((b[0], txt, t, 0, 1))
        else:
            M.append((b[0], txt, t, 0, 0))
    else:
        if M:
            y = M[-1]
            M[-1] = (y[0], y[1] + ' ' + x, y[2], y[3], y[4])
        else:
            sys += 1

P = sorted(set(m[0] for m in M))
print("parsed", len(M), "msgs from", len(P), "people")
print("sys", sys, "| media", med, "| deleted", dele)
print("people:", P)

C = {}
for m in M:
    C[m[0]] = C.get(m[0], 0) + 1

dts = [m[2].date() for m in M]
d1 = min(dts); d2 = max(dts)
N = (d2 - d1).days + 1
tot = len(M)
sp = sorted(C.items(), key=lambda z: -z[1])
pk = max(C.values())

D = {}; H = {}
for m in M:
    D[m[2].date()] = D.get(m[2].date(), 0) + 1
    H[m[2].hour] = H.get(m[2].hour, 0) + 1
bd = max(D, key=D.get); bh = max(H, key=H.get)

idx = {p: i for i, p in enumerate(P)}
HM = np.zeros((6, 24), int)
for m in M:
    HM[idx[m[0]], m[2].hour] += 1

bad = {'a','an','the','and','or','is','are','was','in','on','at','of','to','it',
       'this','that','i','you','he','she','we','they','me','my','for','with','but',
       'not','no','so','if','do','be','have','has','had','will','can','just','also',
       'ok','okay','haan','hai','na','yaar','bhai','kya','scene','matlab','raha',
       'tu','ja','kar','ho','mein','up','down','out','off','one','all','any','some',
       'more','most','only','own','same','too','very','about','over','after','before',
       'when','where','what','which','who','how','why','then','there','here','him',
       'her','us','them','its','them','been','being','am','were','did','does','from',
       'as','by','into','but','not','s','t','im','ive','youre','dont','didnt'}

W = {}
for m in M:
    if m[3] or m[4]:
        continue
    s = ''
    for ch in m[1].lower():
        s += ch if ch.isalnum() or ch == ' ' else ' '
    for w in s.split():
        if len(w) > 1 and w not in bad:
            W[w] = W.get(w, 0) + 1
TW = sorted(W.items(), key=lambda z: -z[1])[:10]

print("=" * 60)
print(" GROUP OVERVIEW")
print("=" * 60)
print(" Group : Hostel Bois 4ever")
print(" Period:", d1.strftime('%d %B %Y'), "to", d2.strftime('%d %B %Y'), "(" + str(N), "days)")
print(" Total :", format(tot, ','), "messages |", len(P), "members")
print("-" * 60)
for p, n in sp:
    print(" " + p.ljust(8) + " " + ("█" * int(n / pk * 20)).ljust(21) + " " + str(n) + " (" + str(round(100 * n / tot, 1)) + "%)")
print()
print(" Busiest day  :", bd.strftime('%d %B %Y'), "(" + str(D[bd]), "msgs)")
print(" Busiest hour :", "{:02d}:00-{:02d}:00".format(bh, bh + 1))
print()
print("=" * 60)
print(" ACTIVITY HEATMAP")
print("=" * 60)
print("          " + " ".join("{:02d}".format(h) for h in range(0, 24, 3)))
NIGHT = [23, 0, 1, 2, 3, 4]
for i, p in enumerate(P):
    row = HM[i]
    mx = row.max() or 1
    cells = []
    for h in range(0, 24, 3):
        v = sum(row[h:h + 3]); r = v / (mx * 3)
        cells.append('. ' if r == 0 else '░ ' if r <= .25 else '▒ ' if r <= .5 else '▓ ' if r <= .75 else '█ ')
    nt = sum(row[h] for h in NIGHT)
    tag = "  <- NIGHT OWL" if row.sum() and nt / row.sum() > 0.6 else ""
    print(" " + p.ljust(8) + " " + " ".join(cells) + tag)
print()
print("=" * 60)
print(" TOP WORDS")
print("=" * 60)
mx = TW[0][1]
for w, n in TW:
    print(" " + w.ljust(12) + " " + ("█" * int(n / mx * 25)) + " " + str(n))

SM = sorted(M, key=lambda z: z[2])
G = {p: [] for p in P}
for i in range(1, len(SM)):
    if SM[i][0] != SM[i - 1][0]:
        g = (SM[i][2] - SM[i - 1][2]).total_seconds()
        if g < 86400:
            G[SM[i][0]].append(g)
AV = {p: (sum(v) / len(v) if v else 9e9) for p, v in G.items()}
FA = min(AV, key=AV.get)
SL = max(AV, key=AV.get)

def fmt(s):
    if s == 9e9: return "N/A"
    if s < 60: return str(round(s, 1)) + "s"
    if s < 3600: return str(round(s / 60, 1)) + "min"
    return str(round(s / 3600, 1)) + "hr"

pd = {p: set() for p in P}
for m in M:
    pd[m[0]].add(m[2].date())
days = [d1 + timedelta(days=i) for i in range(N)]
ST = {}
for p in P:
    mx = cur = 0
    for d in days:
        if d not in pd[p]:
            cur += 1
            if cur > mx: mx = cur
        else:
            cur = 0
    ST[p] = mx

def spam(p):
    r = []; c = 0
    for m in SM:
        if m[0] == p: c += 1
        else:
            if c: r.append(c)
            c = 0
    if c: r.append(c)
    return sum(r) / len(r) if r else 0

def mom(p):
    k = ['okay','safe','eat','sleep','take care','are you','please','reminder','drink water',"don't forget",'calm down']
    return sum(1 for m in M if m[0] == p and not m[3] and not m[4] and any(x in m[1].lower() for x in k))

def owl(p):
    x = [m for m in M if m[0] == p]
    return 100 * sum(1 for m in x if m[2].hour >= 23 or m[2].hour < 5) / len(x) if x else 0

def story(p):
    x = [m for m in M if m[0] == p and not m[3] and not m[4]]
    return sum(len(m[1].split()) for m in x) / len(x) if x else 0

def drama(p):
    x = [m for m in M if m[0] == p and not m[3] and not m[4] and len(m[1]) >= 3]
    if not x: return 0
    c = 0
    for m in x:
        A = [ch for ch in m[1] if ch.isalpha()]
        if (A and all(ch.isupper() for ch in A)) or m[1].count('!') >= 2: c += 1
    return 100 * c / len(x)

def ghost(p): return 100 * (1 - len(pd[p]) / N)

def comedy(p):
    x = [m for m in M if m[0] == p and not m[3] and not m[4]]
    return 100 * sum(1 for m in x if any(w in m[1].lower() for w in ['lol','lmao','haha','rofl','lmfao'])) / len(x) if x else 0

def qm(p):
    x = [m for m in M if m[0] == p and not m[3] and not m[4]]
    return 100 * sum(1 for m in x if m[1].strip().endswith('?')) / len(x) if x else 0

def punct(p):
    x = [m for m in M if m[0] == p]
    return 100 * sum(1 for m in x if m[2].hour < 7) / len(x) if x else 0

FNS = {'SPAMMER': spam, 'GROUP MOM': mom, 'NIGHT OWL': owl, 'STORYTELLER': story,
       'DRAMA QUEEN': drama, 'GHOST': ghost, 'COMEDIAN': comedy,
       'QUESTION MASTER': qm, 'PAKKA PUNCTUAL': punct}

SC = {a: {p: f(p) for p in P} for a, f in FNS.items()}
NR = {a: {p: v / (max(dd.values()) or 1) * 100 for p, v in dd.items()} for a, dd in SC.items()}

left = set(P); avail = set(FNS); A = {}
while left:
    bp = ba = None; bs = -1
    for p in left:
        for a in avail:
            if NR[a][p] > bs:
                bs = NR[a][p]; bp = p; ba = a
    A[bp] = (ba, SC[ba][bp])
    left.discard(bp); avail.discard(ba)

print("=" * 60)
print(" RESPONSE PATTERNS")
print("=" * 60)
print(" Fastest :", FA, "(" + fmt(AV[FA]) + ")")
print(" Slowest :", SL, "(" + fmt(AV[SL]) + ")")
print()
print(" SILENT STREAKS")
for p in P:
    print(" " + p.ljust(8) + ": " + str(ST[p]) + " days")
print()
print("=" * 60)
print(" PERSONALITY ARCHETYPES")
print("=" * 60)
for p in P:
    a, r = A[p]
    print(" " + p.ljust(8) + "-> THE " + a)

def bar(v, mx, w=20):
    if mx == 0 or v == 0: return '·'
    return '█' * max(1, int(v / mx * w))

print("=" * 60)
print(' GROUPDNA REPORT — "Hostel Bois 4ever"')
print(" " + str(N) + " days • " + format(tot, ',') + " messages • " + str(len(P)) + " members")
print("=" * 60)
print(" Period       :", d1.strftime('%d %B %Y'), "to", d2.strftime('%d %B %Y'))
print(" Busiest day  :", bd.strftime('%d %B %Y'), "(" + str(D[bd]), "messages)")
print(" Busiest hour :", "{:02d}:00 - {:02d}:00".format(bh, bh + 1))
print()
print(" MESSAGES PER PERSON")
for p, n in sp:
    print(" " + p.ljust(8) + " " + bar(n, pk).ljust(21) + " " + str(n) + " (" + str(round(100 * n / tot, 1)) + "%)")
print()
print(" ACTIVITY HEATMAP")
print(" " + " ".join("{:02d}".format(h) for h in range(0, 24, 3)))
for i, p in enumerate(P):
    row = HM[i]; mx = row.max() or 1
    cells = []
    for h in range(0, 24, 3):
        r = sum(row[h:h + 3]) / (mx * 3)
        cells.append('. ' if r == 0 else '░ ' if r <= .25 else '▒ ' if r <= .5 else '▓ ' if r <= .75 else '█ ')
    nt = sum(row[h] for h in NIGHT)
    tag = "  <- NIGHT OWL" if row.sum() and nt / row.sum() > 0.6 else ""
    print(" " + p.ljust(8) + " " + " ".join(cells) + tag)
print()
print(" TOP WORDS")
mx = TW[0][1]
for w, n in TW[:5]:
    print(" " + w.ljust(12) + " " + bar(n, mx) + " " + str(n))
print()
print(" RESPONSE PATTERNS")
print(" Fastest :", FA, "(" + fmt(AV[FA]) + ")")
print(" Slowest :", SL, "(" + fmt(AV[SL]) + ")")
print()
print(" SILENT STREAKS")
for p in P:
    if ST[p] > 0:
        print(" " + p.ljust(8) + ": " + str(ST[p]) + " days")
print()
print(" ARCHETYPES")
for p in P:
    print(" " + p.ljust(8) + "-> THE " + A[p][0])